#!/bin/bash
#
# crontab entry
# 0 2 * * * /home/michael/localbin/dl_sched > /dev/null

# Example URL.list:
# https://youtu.be/G-zY2rCceis
# http://blah.com.au/file1.iso


cd ~/Downloads

LIST=URL.list
LOG=~/.dl_sched.log


if [ ! -e $LIST ]
then
    # nothing to do.
    exit
fi

for URL in $(cat $LIST)
do
    # get the file name
    for PART in $(echo $URL | sed 's#/# #g')
    do
       FILE=$PART
    done
    #echo $FILE
    if [ -e $FILE ]
    then
        echo "File already downloaded: $FILE"
    else
        if [[ $URL =~ youtu ]]
        then
           echo youtube
           youtube_dl $URL
        else
           echo "Getting $FILE from $URL"
           wget -c $URL > /dev/null 2>&1
           DATE=$(date '+%d-%m-%y_%H-%M')
           echo "$DATE $URL" >> $LOG
        fi
    fi
done
#echo "" > $LIST
