#!/bin/bash

WORKINGDIR=/data/surveillance
TAR=7
DEL=365
LOG=$(basename $0).log

cd $WORKINGDIR

if [ $? -ne 0 ]
then
    echo "cannot connect to $WORKINGDIR"
    exit 1
fi


DATE=$(date '+%d-%m-%y_%H-%M')
echo "$DATE" >> $LOG

DAY=$(date '+%d-%m-%y')

[ -d $DAY ] || mkdir $DAY
[ -d $DAY/image ] || mkdir $DAY/images
[ -d $DAY/videos ] || mkdir $DAY/videos


mv today/*.jpg $DAY/images 2> /dev/null
mv today/*.avi $DAY/videos 2> /dev/null

# archive some of the older folders
for i in $(find . -maxdepth 1 -type d -mtime +$TAR | sed 's#^./##')
do
    tar zcvfp $i.tgz $i
    rm -rf $i
done

# Delete very old stuff
find . -type d -mtime +$DEL | xargs rm -rf
