#!/bin/bash

ME=$(hostname)
SERVER=nas
REMOTELOCAL=/data/Projects
PROJECT=$1
TMPFILE=/tmp/projectsync.$$
DATE=$(date '+%d-%m-%y_%H-%M')
SCRIPT=$(basename $0)

push() {
    if [ -d $HOME/Projects ]
    then
        cd $HOME/Projects
    else
        echo "there are no projects to push"
        exit 1
    fi
    
    if [ -z $1 ]
    then
        echo "Please nominate a project to push"
        exit 1
    fi
    cd $HOME/Projects
    
    if [ -d $1 ]
    then
        echo "Backing up this project on $SERVER"
        ssh $SERVER "cd $REMOTELOCAL; [ -d $1 ] && tar zcfp projectbackup/$1-$DATE.tgz $1"
        rsync -rvPe ssh $1/ $SERVER:$REMOTELOCAL/$1/ --delete
    else
        echo "No project \"$1\" exists"
        echo "Here are the available projects:"
        ls | grep -v projectbackup
        exit 2
    fi
}

add() {
    if [ -d $HOME/Projects ]
    then
        cd $HOME/Projects
    else
        echo "there are no projects to push"
        exit 1
    fi
    
    if [ -z $1 ]
    then
        echo "Please nominate a project to push"
        exit 1
    fi
    cd $HOME/Projects
    
    if [ -d $1 ]
    then
        if $(ssh $SERVER "cd $REMOTELOCAL; [ -d $1 ]")
        then
            echo "Cannot add $1. It already exists"
        else
            rsync -rvPe ssh $1/ $SERVER:$REMOTELOCAL/$1/
        fi
    else
        echo "No project \"$1\" exists"
        echo "Here are the available projects:"
        ls | grep -v projectbackup
        exit 2
    fi
}

pull() {
    if [ -d $HOME/Projects/$1 ]
    then
        cd $HOME/Projects
        [ -d projectbackup ] || mkdir projectbackup
        tar zcfp projectbackup/$1_$DATE.tgz $1
    fi
    rsync -rvPe ssh $SERVER:$REMOTELOCAL/$1 $HOME/Projects/ --delete
}

diff() {
    rsync --delete -rvne ssh $HOME/Projects/$1 $SERVER:$REMOTELOCAL/
}

list() {
    echo "Available on the server:"
    ssh $SERVER "cd $REMOTELOCAL; ls -d *"
    echo ""
    echo "Locally:"
    cd $HOME/Projects
    ls -d *
}

usage() {
    echo "Usage: $SCRIPT action projectname"
    echo "   or: $SCRIPT list"
    echo "Actions = add, pull, push, diff"
    exit 3
}


if [ $# -eq 0 ]
then
    usage
fi
if [ $# -eq 1 ] && ! [ $1 == "list" ]
then
    usage
fi
if [ $# -gt 2 ]
then
    usage
fi

case $1 in
    add) 
        add $2;;
    pull) 
        pull $2;;
    push) 
        push $2;;
    diff) 
        diff $2;;
    list) 
        list;;
    *)
        usage;;
esac
