#!/bin/bash

ME=$(hostname)
SERVER=maffra
PROJECT=$1
TMPFILE=/tmp/projectsync.$$
DATE=$(date '+%d-%m-%y_%H-%M')

if [ -d $HOME/Projects ]
then
    cd $HOME/Projects
else
    echo "there are not projects to push"
    exit 1
fi

if [ -z $PROJECT ]
then
    echo "Please nominate a project to push"
    exit 1
fi

if [ -d $PROJECT ]
then
    echo "Backing up this project on $SERVER"
    ssh $SERVER "cd /data/Projects; [ -d $PROJECT ] && tar zcfp projectbackup/$ME-$DATE-$PROJECT.tgz $PROJECT"
    rsync -avPe ssh $PROJECT/ $SERVER:/data/Projects/$PROJECT/ --delete
else
    echo "No project \"$PROJECT\" exists"
    echo "Here are the available projects:"
    ls | grep -v projectbackup
    exit 2
fi
