#!/bin/bash

rm /data/maffra/*.log

for i in 1 2 3 4 5 6 7 8 9
do
  echo /data/maffra/file$i.log
  touch /data/maffra/file$i.log
  sleep 1
done
for i in 1 2 3 4 5 6 7 8 9
do
  echo /data/maffra/file$i.tgz
  touch /data/maffra/file$i.tgz
  sleep 1
done

echo before
ls /data/maffra
backup
echo after
ls /data/maffra
