#!/bin/bash

GPS=/dev/serial1

if [ ! -e $GPS ]
then
    exit 0
fi

pkill ntpd
pkill gpsd
gpsd -b -n -D 2 $GPS
sleep 2
GPSDATE=`gpspipe -w | head -10 | grep TPV | sed -r 's/.*"time":"([^"]*)".*/\1/' | head -1`
echo $GPSDATE
date -s "$GPSDATE"
/usr/sbin/ntpd
sleep 1
FIDATE=`date --date='+11 hour'`
#echo $FIDATE
date -s "$FIDATE"
sleep 1
