#!/bin/bash
if [ -z $1 ]
then
  echo "usage: $(basename $0) num"
  exit 2
fi

SECONDS=$1

show_time () {
    num=$1
    min=0
    hour=0
    day=0
    if ((num>59));then
        ((sec=num%60))
        ((num=num/60))
        if ((num>59));then
            ((min=num%60))
            ((num=num/60))
            if ((num>23));then
                ((hour=num%24))
                ((day=num/24))
            else
                ((hour=num))
            fi
        else
            ((min=num))
        fi
    else
        ((sec=num))
    fi
    echo "$day"d "$hour"h "$min"m "$sec"s
}

show_time $SECONDS
