#!/bin/bash

ME=$(basename $0)
LOCK=/home/michael/.$ME.lock

GO=false
for NET in $(hostname -I)
do
   [ $NET == "10.0.0.4" ] && GO=true
   [ $NET == "10.0.0.5" ] && GO=true
done

if ! [ $GO = true ]
then
    exit
fi

ping -c 1 nas > /dev/null 2>&1
if [ $? -ne 0 ]
then
    echo "Cannot find nas. Maybe we are not at home!"
    exit 1
fi


if [ -e $LOCK ]
then
    #echo "Lock exists: $LOCK"
    LOCKPID=$(head -1 $LOCK)
    #echo LOCKPID = $LOCKPID
    if [ ! -z $(ps ax | grep -v grep | grep $LOCKPID | gawk '{print $1}') ]
    then
        echo "Instance is already running: $LOCKPID"
        exit 1
    fi
    echo "Removing stale lock: $LOCK $LOCKPID"
    rm $LOCK
fi

# set up the lock
echo $$ > $LOCK

# go.
nice rsync --delete -avxPe ssh /home/michael/ nas:/common/sync/hourly/mate/ --exclude VMs

# remove the lock
rm $LOCK
